### ISSUE TITLE
Add newline to output

### ISSUE THREAD

**Issue by webpro** [thlorenz/exorcist#10]
The fact that no newline is added to the output after the `sourceMappingURL` comment, results in a [Parse Error](https://github.com/ariya/phantomjs/issues/11081) when that module is used in PhantomJS. So obviously it's not really an issue of exorcist, but in general it is good practice to have a newline at the end of a file. Browserify itself also keeps/adds it (debug mode or not).

The thing is, we could simply add it:

    return { json: json, src: newSrc + '\n' + comment + '\n' }

But it might be a problem to some, theoretically (not sure how). Anyway, I'm happy to submit a PR (with updated tests). Should we just change current behavior or make it an option?

**Comment by jasonkarns** [comment]
As a user, I wouldn't expect an option for such a tiny detail. Agreed that it should be emitting a (non-optional) newline.

**Comment by bendrucker** [comment]
This was resolved in 3f01dce5e39500ca2829df99307d9c8344cf1636
