### ISSUE TITLE
What's the reasoning for automatically changing sourceRoot?

### ISSUE THREAD

**Issue by jmm** [thlorenz/exorcist#11]
What's the reasoning for doing this:

```js
var json = inlined
  .setProperty('sourceRoot', root || '')
  .toJSON(2);

```

Why would `sourceRoot` necessarily change because an inline source map is being extracted? `sourceRoot` is for the user agent to use in combination with `sources` values to request the source files, right?

I was using exorcist to help rapidly debug issues with, wait for it...`sourceRoot` output in traceur and exorcist was obscuring the output from traceur (so I had to stop using it for that).

**Comment by bendrucker** [comment]
Unclear what the original reason was but now it's changed to pass the original value through ;)

**Comment by jmm** [comment]
Cool, thanks!
