### ISSUE TITLE
Output file name overwritten by generated.js

### ISSUE THREAD

**Issue by niksy** [thlorenz/exorcist#14]
When using CLI, generated source maps `file` property points to `generated.js` even though command given should output to some other file.

For example:

``` sh
node_modules/.bin/browserify ./foo.js --debug | node_modules/.bin/exorcist bundle.js.map > foo.o1.js
```

**Comment by thlorenz** [comment]
That's not a problem. The generated.js is just a placeholder and actually not used by any tool.

**Comment by wnr** [comment]
Hi, this seems to be the case when using the JavaScript API as well.

> The generated.js is just a placeholder and actually not used by any tool.

This is not true, as Uglify's `--in-source-map` uses the property, and potentially future tools might depend on this property being correct. I suggest reopening this issue.

**Comment by wnr** [comment]
When changing the file property to the correct value manually, the source maps no longer works as expected. The file mapping seems to be a bit off as the wrong content is displayed (file A shows the content of file B, etc.). I haven't been able to identify a pattern.

It is perhaps not possible to alter such values of source maps manually after generation, but I'm adding this information here for the record as a warning for others.

**Comment by bendrucker** [comment]
What is the correct value here?

**Comment by wnr** [comment]
If the source code file is called `a.js` and the source maps of that file is called `a.js.map` I believe the expected value is `a.js` of the `file` property.

**Comment by bendrucker** [comment]
So to be clear, the original post title implying that this was specific to the CLI is inaccurate?

**Comment by wnr** [comment]
Yes.

**Comment by bendrucker** [comment]
FYI, that filename comes all the way from here:

https://github.com/thlorenz/combine-source-map/blob/master/index.js#L60

Haven't had time to properly debug it myself but wanted to leave a hint for anyone who wants to play around.

**Comment by bendrucker** [comment]
Actually that doesn't seem to be called from the tests so that may be a false flag. I'm not planning on looking into this any further but will happily review a PR if someone figures out how to resolve this.
