### ISSUE TITLE
proposal: add an option to completely remove the mapfile reference at the end of the js files.

### ISSUE THREAD

**Issue by sinan** [thlorenz/exorcist#15]
hey @thlorenz, what do you think about such a feature, if you think it should be supported by exorcist I can finish it and open a PR?

https://github.com/sinan/exorcist/commit/58063af17e70490eac59a67d045d00a1fb080d2a

This is useful when you want to use your sourcemaps in production with an external service such as rollbar, errorception, etc. but you want your production code to not include mappings to avoid 404s in the browser console.

**Comment by thlorenz** [comment]
That's not what exorcist is for. Please just use [convert-source-map](//github.com/thlorenz/convert-source-map) for that.
