### ISSUE TITLE
Inline sourcemaps not fully replaced

### ISSUE THREAD

**Issue by baelter** [thlorenz/exorcist#16]
The source map is created and the soureMappingURL is updated correctly but after that a bunch of  base64 is still in the bundle file.

`browserify --debug app.js > bundle.js`

`tail -n1 bundle.js`
//#sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi...

`browserify --debug app.js > bundle2.js | exorcist bundle2.js.map > bundle2.js`

`tail -n2 bundle2.js`
//# sourceMappingURL=bundle2.js.map
uIjozLCJzb3VyY2VzIjpbIi4uLy4uLy5ucG0tcGFja2FnZXMvb...

Don't know if this is an issue within exorcist, mold-source-map or convert-source-map.

**Comment by jskrzypek** [comment]
How are you setting up/asking for the exorcist transform? Our side is working fine (though we use it with gulp)

**Comment by baelter** [comment]
@jskrzypek: Sorry, if I don't understand your question.. As stated above, I just use the npm package like so: `browserify --debug app.js > bundle2.js | exorcist bundle2.js.map > bundle2.js`

Have also tried via gulp, but that didn't work either. Ended up using gulp-sourcemaps which seems to work as expected.

**Comment by jasonkarns** [comment]
@baelter I'm confused as to how the command you posted is intended to work. You're redirecting STDOUT to `bundle2.js` from browserify, which means there is nothing to pipe to exorcist. When I run the command as you posted, I get an error: `The code that you piped into exorcist contains no source map!`

**Comment by jskrzypek** [comment]
@jasonkarns you could try this: 
```sh
browserify --debug app.js > bundle2.js && cat bundle2.js | exorcist bundle2.js.map > bundle2.js
```

**Comment by jasonkarns** [comment]
@jskrzypek i'm not experiencing the issue. I was pointing out to the OP that his snippet would likely not work as expected but not necessarily indicate a bug in exorcist

**Comment by baelter** [comment]
I'll close this for now.
