### ISSUE TITLE
is this library still maintained? [source map output not working]

### ISSUE THREAD

**Issue by episodeyang** [thlorenz/exorcist#28]
I am trying to follow the recipes but exorcist is not outputting any file. The last update is May 14 this year and there hasn't been any activity ever since.

**Comment by thlorenz** [comment]
It is still maintained, I'm just swamped with other things.
I'm looking for people to help, so if you wanna jump in and vet some of the pull requests I'd appreciate that.

**Comment by episodeyang** [comment]
Thanks for sharing this library! I will help as much as I can. right now I'm using the `gulp-sourcemap` and will probably move to `webpack` in the future.
