### ISSUE TITLE
Taking a writeable stream rather than file path

### ISSUE THREAD

**Issue by hayes** [thlorenz/exorcist#3]
it would be really useful if exorcist could take a writeable stream instead of a file path.
I am not sure how you feel about arg that could be either a string or a stream, so another option would be to add another method. (for example mkdirp also exports mkdirp.sync)
I'd be happy to submit a PR to do this if you think it would be a useful addition.

**Comment by dantman** [comment]
I tried implementing this some time ago:

https://github.com/thlorenz/exorcist/compare/master...dantman:master

However I was never quite sure I got the error handling right.
