### ISSUE TITLE
npm doesn't render the README properly

### ISSUE THREAD

**Issue by whmountains** [thlorenz/exorcist#32]
npm displays the html tags `<code></code>`  in the first sentence of the readme instead of showing a code block like it should.

![screen shot 2016-03-06 at 6 42 01 am 1](https://cloud.githubusercontent.com/assets/8680147/13553386/8f00077e-e366-11e5-8b9f-1116f92d567a.png)

I'm guessing the leading period trips it up somehow.  I have some ideas for how to work around it but I don't have access to see my changes as I make them so I figured I'd make an issue instead of a pull request.

**Comment by abritinthebay** [comment]
It's actually an error with their parser/renderer. The readme uses backticks (as it should) and their parser is converting that to the html <code> element. Which it then mis-renders (or escapes).

It's an NPM bug, not a Exorcist bug.
