### ISSUE TITLE
Dramatically increases size of files without source maps

### ISSUE THREAD

**Issue by c-f-h** [thlorenz/exorcist#33]
Here I create two bundles, once without --debug and once with, then exorcise them and compare the sizes:

```
$ `npm bin`/browserify ../../src/js/app.js > bundle.js
$ `npm bin`/exorcist app.map < bundle.js > bundle.ex.js
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.
$ ls -lah
total 11M
drwxr-xr-x 2 user Numa 4.0K Mar  9 13:56 .
drwxr-xr-x 3 user Numa 4.0K Mar  9 11:18 ..
-rw-r--r-- 1 user Numa 8.8M Mar  9 13:56 bundle.ex.js
-rw-r--r-- 1 user Numa 2.2M Mar  9 13:56 bundle.js


$ `npm bin`/browserify --debug ../../src/js/app.js > bundle-debug.js
$ `npm bin`/exorcist app.map < bundle-debug.js > bundle-debug.ex.js
$ ls -lah
total 22M
drwxr-xr-x 2 user Numa 4.0K Mar  9 13:57 .
drwxr-xr-x 3 user Numa 4.0K Mar  9 11:18 ..
-rw-r--r-- 1 user Numa 2.6M Mar  9 13:57 app.map
-rw-r--r-- 1 user Numa 2.2M Mar  9 13:57 bundle-debug.ex.js
-rw-r--r-- 1 user Numa 5.6M Mar  9 13:57 bundle-debug.js
-rw-r--r-- 1 user Numa 8.8M Mar  9 13:56 bundle.ex.js
-rw-r--r-- 1 user Numa 2.2M Mar  9 13:56 bundle.js
```

The bundle without source maps has **2.2M**, with source maps **5.6M**.
After exorcising, the one without source maps **grew to 8.8M**, whereas the one with source maps **shrank to 2.2M** (the size of the original bundle without maps, as expected).

So the bundle without source maps **grew by a factor 4** although exorcist claimed that it's just "piping it through".

I couldn't reproduce this on a minimal example so far.

**Comment by abritinthebay** [comment]
While serious - what was the actual content in those files that got changed? Perhaps it got stuck in a loop on some code and dumped the original code in repeatedly? The fact that 8.8 is a multiple of 2.2 tends to suggest that...

**Comment by bendrucker** [comment]
We can keep this open for a bit longer but I'm going to go ahead and close it out if no one can post a public repro
