### ISSUE TITLE
Test coverage reduced with replacement to #34

### ISSUE THREAD

**Issue by meeber** [thlorenz/exorcist#37]
@bendrucker I like the new auto-directory creation functionality in the latest commit, but it's worth noting that #34 was focused on preventing errors from being swallowed during the file-writing process, regardless of reason (e.g., permission issue or disk space full, not just non-existent directory). This was done as a precursor to adding the `--error-on-missing` option in #36.

A consequence of the latest commit is that the test that verified proper error handling during the file-writing process was lost. I'm not sure if it's worth adding it back in (and/or adding a test for failed directory creation), both due to the low frequency of such errors, as well as increased difficulty in testing them, but I figured it was worth noting! :D

**Comment by bendrucker** [comment]
Happy to add a more direct unit test to cover that, one sec
