### ISSUE TITLE
./generateAndvalidate_one.js.map did not generated

### ISSUE THREAD

**Issue by sophieyoung717** [thlorenz/exorcist#39]
Hi,
why is ./generateAndvalidate_one.js.map not generated?

var fs = require('fs'); 
var path = require('path');
 var exorcist   = require('exorcist');
 var browserify = require('browserify');
 var mapfile    = path.join(__dirname, './generateAndvalidate_one.js.map'); 
var b = browserify(); 
b.add('./GenerateAndValidate.js'); 
b.bundle().pipe(exorcist(mapfile)) 
.pipe(fs.createWriteStream(path.join(__dirname, './generateAndvalidate_one.js'), 'utf8'));

**Comment by bendrucker** [comment]
`browserify({debug: true})` needs to be on to tell browserify to generate a source map
