### ISSUE TITLE
what is .js.map for?

### ISSUE THREAD

**Issue by sophieyoung717** [thlorenz/exorcist#40]
Hi, 

Thank you very much for the quick response for my last issue.

I generated me .js.map file. But since it is a big file and the structure is pretty simple, I got last just as when I look at the result of browserify file. I thought .js.map will help me get better understanding of what is going on in .js file generated by browserify, in .js.map, there is only sources, sourcesContent? Could you show me the structure of this file and maybe how to use it please? Thanks. I appreciate it very much.

**Comment by bendrucker** [comment]
This might be helpful: http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
