### ISSUE TITLE
npm behind master?

### ISSUE THREAD

**Issue by OliverJAsh** [thlorenz/exorcist#42]
The latest version of exorcist on npm seems to be behind `master`. Specifically, I'm looking for [this line](https://github.com/thlorenz/exorcist/blob/55d07429ee3416e438c6ed02f4492372e71ec370/bin/exorcist.js#L40), but it doesn't exit in the published version:

```
npm pack exorcist@0.4.0
```

**Comment by OliverJAsh** [comment]
Workaround: `npm i thlorenz/exorcist#master`

**Comment by Reboog711** [comment]
I came across [this bug](https://github.com/thlorenz/exorcist/issues/18) and solved it using the solution from @OliverJAsh .  

Code appears to be updated; npm is not.

**Comment by bendrucker** [comment]
@thlorenz Can you add me on npm so I can publish a new version?

`npm owner add bendrucker exorcist`

**Comment by meeber** [comment]
@bendrucker @thlorenz Also, #43 needs to be merged prior to publishing; the master branch contains a bug that causes it to accept the short version (`-e`) but not the long version (`--error-on-missing`).

**Comment by JakeChampion** [comment]
Is there anything blocking this from getting published to npm?

**Comment by bendrucker** [comment]
Published 1.0 w/ latest
