### ISSUE TITLE
exorcist writes the map to disk instead of passing it to the next stream

### ISSUE THREAD

**Issue by ericmorand** [thlorenz/exorcist#45]
> Externalizes the source map found inside a stream to an external .map file or **stream**.

This is the description of this tool but the tool actually write the source map to the disk instead of externalizing it to a stream.

**Comment by bendrucker** [comment]
https://github.com/thlorenz/exorcist/blob/4fcc8d306e6bd9c81c7a6b5fcd85f3ce6284cd40/index.js

Exorcist does both. It will write a file if you pass a path, or write to a writable stream if you pass that instead.
