### ISSUE TITLE
Bump minimist version to avoid Prototype Pollution

### ISSUE THREAD

**Issue by archmoj** [thlorenz/exorcist#47]
https://www.npmjs.com/advisories/1179

**Comment by bendrucker** [comment]
Thanks, ended up just updating all the deps to the latest versions. This will go out as a major release soon.

**Comment by bendrucker** [comment]
@thlorenz Can you add me to exorcist on npm so I can get 2.0.0 published?

**Comment by thlorenz** [comment]
Done .. thanks for all your help!

**Comment by bendrucker** [comment]
🙏🏻, published `2.0.0`
